language: groovy

jdk:
  - openjdk11

env:
  matrix:
    - CI=true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - curl -L -o download-gradle-wrapper.sh "https://raw.githubusercontent.com/renke0/toolbox/master/gradle/download-gradle-wrapper.sh"
  - chmod +x download-gradle-wrapper.sh
  - sh download-gradle-wrapper.sh 5.6

install:
  - ./gradlew assemble

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
